version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_smart_home
    restart: always
    environment:
      POSTGRES_DB: smart_home_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: smart_home_app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smart_home_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  pgdata:
